# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package and Docker image publish

on:
  push:
    branches:
    - main

jobs:
  maven:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        cache: 'maven'
        
    - name: Check Java version
      run: java -version
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}

    - name: Upload artifact for Docker job
      uses: actions/upload-artifact@v3
      with:
        name: java-app
        path: '${{ github.workspace }}/target/*.jar'

  docker:

    runs-on: ubuntu-latest
    needs: maven
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Download artifact from maven job
      uses: actions/download-artifact@v3
      with:
        name: java-app
    - name: Logging in to Docker
      run: docker login ghcr.io -u lbokor69 -p ${{ secrets.GH_PAT }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/lbokor69/cubix/cloudnative/demo:actions
    - name: Publishing the Docker image
      run: docker push ghcr.io/lbokor69/cubix/cloudnative/demo:actions
